### ISSUE TITLE
00 - Intro

### ISSUE THREAD

**Issue by nisnardi** [leoasis/workshop-pensando-en-react#6]
Te parece agregar algún screenshot de como usar el plugin de React en chrome? como para que lo vean?

**Comment by leoasis** [comment]
Si, podríamos agarrar el gif que está en [react-devtools](https://github.com/facebook/react-devtools) o sino linkear directo ahi no?

**Comment by nisnardi** [comment]
Creo que con el link estamos bien. Lo agrego!
